version: '3'
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - ./volumes/mongo/data:/data/db
      - ./volumes/mongo/initdb:/docker-entrypoint-initdb.d